//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting_Minutes_Details_Tbl
    {
        public int Id { get; set; }
        public Nullable<int> MeetingMinutesMasterId { get; set; }
        public Nullable<int> ProductServiceId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Unit { get; set; }
    
        public virtual Meeting_Minutes_Master_Tbl Meeting_Minutes_Master_Tbl { get; set; }
    }
}
