//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Service_Tbl
    {
        public int Id { get; set; }
        public string ProductServiceName { get; set; }
        public string Unit { get; set; }
    }
}
