//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collect_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Collect_Request()
        {
            this.Data_History = new HashSet<Data_History>();
        }
    
        public int Collectid { get; set; }
        public Nullable<int> Restid { get; set; }
        public string PreserveTime { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        public Nullable<int> Received_By { get; set; }
        public Nullable<int> Approved_by { get; set; }
        public Nullable<System.DateTime> CollectDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Resturant Resturant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Data_History> Data_History { get; set; }
    }
}
