//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZerohungerEntities1 : DbContext
    {
        public ZerohungerEntities1()
            : base("name=ZerohungerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Collect_Request> Collect_Request { get; set; }
        public virtual DbSet<Data_History> Data_History { get; set; }
        public virtual DbSet<Resturant> Resturants { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
